/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e2p1_lloydcooper;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author CUSTOMER PC
 */
public class MenuGrafico extends javax.swing.JFrame {

    /**
     * Creates new form MenuGrafico
     */
    public MenuGrafico() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LibrosYMasLibros = new javax.swing.JButton();
        GusanitoHambriento = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("EXAMEN 2 - LLOYD COOPER");

        LibrosYMasLibros.setText("Libros y mas libros");
        LibrosYMasLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LibrosYMasLibrosMouseClicked(evt);
            }
        });
        LibrosYMasLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrosYMasLibrosActionPerformed(evt);
            }
        });

        GusanitoHambriento.setText("Gusanito Hambriento");
        GusanitoHambriento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GusanitoHambrientoMouseClicked(evt);
            }
        });
        GusanitoHambriento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GusanitoHambrientoActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GusanitoHambriento, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(LibrosYMasLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LibrosYMasLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GusanitoHambriento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LibrosYMasLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrosYMasLibrosActionPerformed
        
    }//GEN-LAST:event_LibrosYMasLibrosActionPerformed

    private void LibrosYMasLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrosYMasLibrosMouseClicked
        JOptionPane.showMessageDialog(null, "Usted esta entrando al ejercicio Libros y mas libros");
        Libreria Libreria = new Libreria();
        dispose(); //para cerrar la ventana del joption
        Libreria.menu();
    }//GEN-LAST:event_LibrosYMasLibrosMouseClicked

    private void GusanitoHambrientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GusanitoHambrientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GusanitoHambrientoActionPerformed

    private void GusanitoHambrientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GusanitoHambrientoMouseClicked
        JOptionPane.showMessageDialog(null, "Usted esta entrando al ejercicio Gusanito Hambriento");
        dispose();
        Scanner scanner = new Scanner(System.in);
        System.out.print("Ingresa el valor de N: ");
        int N = scanner.nextInt();
        System.out.print("Ingresa el valor de M: ");
        int M = scanner.nextInt();
        Gusanito g = new Gusanito(N,M);
        
        // aquí agregamos el código para mover al gusanito
        System.out.println("Ingresa una instrucción (por ejemplo: 5U para mover arriba 5 veces, o 3R para mover a la derecha 3 veces)");
        String instruccion = scanner.next();

        while (instruccion != null) {
            if (!instruccion.isEmpty()) { // Agrega esta verificación
                g.agregarInstruccion(instruccion);
                g.mover(instruccion);
            }
            System.out.println("Ingresa una instrucción (por ejemplo: 5U para mover arriba 5 veces, o 3R para mover a la derecha 3 veces)");
            instruccion = scanner.nextLine();
        }
    }//GEN-LAST:event_GusanitoHambrientoMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GusanitoHambriento;
    private javax.swing.JButton LibrosYMasLibros;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
